// app/react-hook/src/components/Playground.tsx
import React, { forwardRef, useContext, useEffect } from "react";

import { VIEWPORT_HEIGHT, VIEWPORT_WIDTH } from "@lib/constants";
import { Color } from "@lib/enumerables";

import { PadsContext, UpdateQueue } from "../ctx";
import { useBall } from "../hooks";
import { Rect } from "../shapes";

interface Props {
  render: (state: Moving<Circ>) => JSX.Element;
}

export const Playground = forwardRef<Moving<Circ>, Props>(({ render }, ref) => {
  let que = useContext(UpdateQueue);
  let getPads = useContext(PadsContext);

  let [ball, update] = useBall(VIEWPORT_WIDTH / 2, VIEWPORT_HEIGHT / 2);

  useEffect(() => {
    if (ref != null && "current" in ref) ref.current = ball;
  }, [ball]);

  useEffect(() => {
    que?.add(() => {
      update(...getPads());
    });
  }, []);

  let area = { x: 0, y: 0, w: VIEWPORT_WIDTH, h: VIEWPORT_HEIGHT };
  return (
    <>
      <Rect {...area} color={Color.BLACK} />
      <>{render(ball)}</>
    </>
  );
});

// app/vue-vuex/src/components/Playground.vue
<script>
import { Color } from "@lib/enumerables";
import { VIEWPORT_WIDTH, VIEWPORT_HEIGHT } from "@lib/constants";

export default {
  inject: ["ctx"],
  render() {
    let ctx = this.ctx();
    ctx.fillStyle = Color.BLACK;
    ctx.fillRect(0, 0, VIEWPORT_WIDTH, VIEWPORT_HEIGHT);
  },
};
</script>
